// Define Product type locally if './store' is missing
import { Product } from "./store";

export const mockProducts: Product[] = [
  {
    _id: '1',
    name: 'Air Jordan 1 Retro High OG',
    brand: 'Jordan',
    price: 2899,
    originalPrice: 3299,
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11'],
    colors: ['Black/Red', 'White/Black'],
    category: 'Basketball',
    description: 'The iconic Air Jordan 1 that started it all. Premium leather construction with classic colorway.',
    inStock: true,
    featured: true,
    rating: 4.8,
    reviews: 324,
  },
  {
    _id: '2',
    name: 'Nike Air Max 90',
    brand: 'Nike',
    price: 2199,
    images: [
      'https://images.pexels.com/photos/2529147/pexels-photo-2529147.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10'],
    colors: ['White/Grey', 'Black/White', 'Navy/White'],
    category: 'Lifestyle',
    description: 'The Air Max 90 stays true to its OG running roots with iconic Waffle outsole.',
    inStock: true,
    featured: true,
    rating: 4.6,
    reviews: 189,
  },
  {
    _id: '3',
    name: 'Adidas Yeezy Boost 350 V2',
    brand: 'Adidas',
    price: 4299,
    images: [
      'https://images.pexels.com/photos/1598506/pexels-photo-1598506.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5'],
    colors: ['Zebra', 'Cream White', 'Static'],
    category: 'Lifestyle',
    description: 'Kanye West\'s revolutionary design meets adidas innovation in this sought-after silhouette.',
    inStock: true,
    featured: true,
    rating: 4.9,
    reviews: 567,
  },
  {
    _id: '4',
    name: 'Converse Chuck Taylor All Star',
    brand: 'Converse',
    price: 1299,
    images: [
      'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2529147/pexels-photo-2529147.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['Black', 'White', 'Red', 'Navy'],
    category: 'Casual',
    description: 'The timeless classic that has been a cultural icon for decades.',
    inStock: true,
    featured: false,
    rating: 4.4,
    reviews: 892,
  },
  {
    _id: '5',
    name: 'Puma RS-X',
    brand: 'Puma',
    price: 1899,
    images: [
      'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    sizes: ['7', '7.5', '8', '8.5', '9', '9.5', '10'],
    colors: ['Multi', 'Black/White', 'Red/Blue'],
    category: 'Running',
    description: 'Bold, chunky design with retro-futuristic aesthetics and superior comfort.',
    inStock: false,
    featured: false,
    rating: 4.3,
    reviews: 156,
  },
  {
    _id: '6',
    name: 'Vans Old Skool',
    brand: 'Vans',
    price: 1599,
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1598506/pexels-photo-1598506.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Black/White', 'Navy/White', 'Checkerboard'],
    category: 'Skate',
    description: 'The classic skate shoe with the iconic sidestripe, built for durability and style.',
    inStock: true,
    featured: false,
    rating: 4.5,
    reviews: 445,
  },
];

export const provinces = [
  'Eastern Cape',
  'Free State',
  'Gauteng',
  'KwaZulu-Natal',
  'Limpopo',
  'Mpumalanga',
  'Northern Cape',
  'North West',
  'Western Cape',
];

export const mockReviews = [
  {
    id: '1',
    productId: '1',
    user: 'Thabo M.',
    rating: 5,
    comment: 'Amazing quality! Exactly as described. Fast delivery to Cape Town.',
    date: '2024-01-15',
    verified: true,
  },
  {
    id: '2',
    productId: '1',
    user: 'Sarah L.',
    rating: 4,
    comment: 'Great sneakers, comfortable fit. The authentication guarantee gave me confidence to buy.',
    date: '2024-01-10',
    verified: true,
  },
  {
    id: '3',
    productId: '2',
    user: 'Michael K.',
    rating: 5,
    comment: 'Perfect condition, fast shipping to Durban. Will definitely order again from Letlapa!',
    date: '2024-01-08',
    verified: true,
  },
];